version: '3.9'

services:
    nginx:
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php

    db:
        image: mysql:latest
        restart: always
        environment:
         -MYSQL_ROOT_PASSWORD: example
         -MYSQL_DATABASE: my_db
        volumes:
            - db-data:/var/lib/mysql
    
    php:
        build:
            context: .
        volumes:
            - .:/var/www/html
        depends_on:
            - db
    
    